name = "portfolio"

[build]
command = "npm run build"
output_dir = "dist"
base = "/"

[build.environment]
NODE_VERSION = "18"
NPM_VERSION = "9"

[site]
bucket = "./dist"
entry-point = "dist/index.html"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200 